class Music {
  int id;
  String title, singer, album, time;
  bool isFavorite;
  bool playlist;

  Music(
      {required this.id,
      required this.album,
      required this.isFavorite,
      required this.playlist,
      required this.singer,
      required this.title,
      required this.time});
}

List<Music> demoMusics = [
  Music(
      id: 1,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 2,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 3,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 4,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 5,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 6,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 7,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 8,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 9,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 10,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 11,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 12,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 13,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 14,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 15,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 16,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 17,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 18,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 19,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 20,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 21,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 22,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 23,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 24,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 25,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 26,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 27,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 28,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 29,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
  Music(
      id: 30,
      album: 'N/A',
      isFavorite: false,
      playlist: false,
      time: '3:25',
      singer: 'ABBA',
      title: 'Kahit Ano'),
];
